#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
    resource: '../src/Controller/'
    type:     annotation
    # Register api
register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: ['POST']
api_login_check:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: ['POST']
